global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastify-app"
    static_configs:
      - targets: ["172.17.0.1:3001"] #gateway docker que permite acesso ao host
    scrape_interval: 5s
    metrics_path: "/metrics"
